version: '3.9'

services:
  react-frontend:
    build: .
    ports:
      - "3000:3000"
    container_name: react-frontend
    networks:
      - app-network1
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    command: npm start

networks:
  app-network1:
    external: true
